name: Build

on:
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '45 2 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build and test typescript
      working-directory: typescript
      run: |
        npm install
        gulp
        gulp jest
        gulp wp

    - name: Build and lint wordpress plugin
      working-directory: metalation-calculator-wp
      run: |
        npm install
        npm run build
        npm run format
        npm run lint:js
        npm run lint:css

    - name: Check plugin files are up-to-date
      run: |
        if [[ `git status --porcelain metalation-calculator-wp` ]]; then
          echo "Wordpress plugin files are not up to date:"
          git status --porcelain metalation-calculator-wp
          echo "Run 'gulp wp' in 'typescript', and 'npm run build'/'npm run format' in 'metalation-calculator-wp' and commit the changes."
          exit 1
        fi

    - name: Check for npm audit issues in typescript production dependencies
      run: |
        cd typescript && npm audit --production

    - name: Check for updates in Wordpress dependencies
      working-directory: metalation-calculator-wp
      run: |
        npm run packages-update
        if [[ `git status --porcelain metalation-calculator-wp` ]]; then
          echo "Wordpress packages are not up to date:"
          git status --porcelain metalation-calculator-wp
          echo "Run 'npm run packages-update' and commit the changes."
          exit 1
        fi

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      if: contains(github.ref, 'main') || github.event_name == 'release'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./typescript/dist

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Create Wordpress plugin zip
      working-directory: metalation-calculator-wp
      run: zip -X -r ../metalation-calculator-wp.zip . -x *.git* node_modules/\* .* "*/\.*"

    - name: Upload Wordpress plugin zip as artifact (zipped again)
      uses: actions/upload-artifact@v2
      with:
        name: metalation-calculator-archive
        path: metalation-calculator-wp.zip

    - name: Release Wordpress plugin
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: metalation-calculator-wp.zip
