name: Build site with gulp

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and test
      run: |
        npm install
        gulp
        gulp jest

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: startsWith(matrix.node-version, '16.') && (contains(github.ref, 'main') || github.event_name == 'release')
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
