name: Build site with gulp

on:
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '45 2 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and test typescript
      working-directory: typescript
      run: |
        npm install
        gulp
        gulp jest
        gulp wp

    - name: Build and lint wordpress plugin
      if: startsWith(matrix.node-version, '16.')
      working-directory: metalation-calculator-wp
      run: |
        npm install
        npm run build
        npm run format
        npm run lint:js
        npm run lint:css

    - name: Check plugin files are up-to-date
      if: startsWith(matrix.node-version, '16.')
      run: |
        if [[ `git status --porcelain metalation-calculator-wp` ]]; then
          echo "Wordpress plugin files are not up to date:"
          git status --porcelain metalation-calculator-wp
          echo "Run 'gulp wp' in 'typescript', and 'npm run build'/'npm run format' in 'metalation-calculator-wp' and commit the changes."
          exit 1
        fi

    - name: Check for npm audit issues in production dependencies
      if: startsWith(matrix.node-version, '16.')
      run: |
        cd typescript && npm audit --production
        cd ../metalation-calculator-wp && npm audit --production

    - name: Check for updates in Wordpress dependencies
      if: startsWith(matrix.node-version, '16.')
      working-directory: metalation-calculator-wp
      run: |
        npm run packages-update
        npm audit fix
        if [[ `git status --porcelain metalation-calculator-wp` ]]; then
          echo "Wordpress packages are not up to date:"
          git status --porcelain metalation-calculator-wp
          echo "Run 'npm run packages-update' and 'npm audit fix' and commit the changes."
          exit 1
        fi

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: startsWith(matrix.node-version, '16.') && (contains(github.ref, 'main') || github.event_name == 'release')
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./typescript/dist
