name: Build site with gulp

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-typescript:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: typescript

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and test
      run: |
        npm install
        gulp
        gulp jest

    - name: Build for wordpress and check plugin is up-to-date
      run: |
        gulp wp
        if [[ `git status --porcelain ../metalation-calculator-wp` ]]; then
          echo "Wordpress plugin files are not up to date with typescript directory:"
          git status --porcelain ../metalation-calculator-wp
          echo "Run 'gulp wp' and commit the changes."
          exit 1
        fi

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: startsWith(matrix.node-version, '16.') && (contains(github.ref, 'main') || github.event_name == 'release')
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./typescript/dist
